In [1]:
print("too many bitches, where the fellas at?")

too many bitches, where the fellas at?


In [5]:
import os
import netket as nk
from netket.operator.spin import sigmax, sigmaz, sigmay
import numpy as np
# from src.wilson import * 
#from src.models import * 
import matplotlib.pyplot as plt

In [3]:
L = 8
g = nk.graph.Square(L, pbc=True)
print(f'g.n_edges = {g.n_edges}, LxLx2 = {L**2 * 2}')
hi = nk.hilbert.Spin(s=1/2, N=g.n_edges)

g.n_edges = 128, LxLx2 = 128


In [8]:
L = 4
matrix = np.random.rand(3, L, L)

# Splitting into two matrices
matrix_1xLxL = matrix[0:2, :, :]  # Extract the first slice
matrix_2xLxL = matrix[2:3, :, :]   # Extract the second and third slices


[[[0.98215616 0.69156328 0.82497317 0.92194979]
  [0.06211781 0.31802597 0.07801264 0.76393965]
  [0.64832239 0.56938487 0.77260175 0.84500525]
  [0.31902154 0.60617271 0.56361929 0.5336794 ]]]
[[[0.51027979 0.76312435 0.78289578 0.88384733]
  [0.70351522 0.96250128 0.60359535 0.20472387]
  [0.43884378 0.91031578 0.9090197  0.74296623]
  [0.12819441 0.62246193 0.18623606 0.53419632]]

 [[0.28452463 0.3496681  0.94995942 0.70863871]
  [0.53123184 0.18686091 0.73931824 0.12360296]
  [0.77939228 0.15468867 0.91375433 0.94344255]
  [0.55632194 0.97866305 0.15036199 0.63419333]]]
